name: First Github Action workflow

on: [push]

jobs:
  build:
    name: First Build job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install
      run: npm install
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag samarbahloul/docker-s1:${GITHUB_SHA::8}
    - name: Push Docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/dockers1:${GITHUB_SHA::8}
